CREATE TABLE board1(
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    pos VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    info VARCHAR(1000) NOT NULL,
    id VARCHAR(20) NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE board2(
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    pos VARCHAR(20) NOT NULL,
    crewname VARCHAR(50) NOT NULL
    title VARCHAR(100) NOT NULL,
    info VARCHAR(1000) NOT NULL,
    id VARCHAR(20) NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE choice(
    height VARCHAR(10) NOT NULL,
    weight VARCHAR(10) NOT NULL,
    age VARCHAR(10) NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Course(
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    path JSON,
    distance VARCHAR(100) NOT NULL,
    time VARCHAR(100) NOT NULL,
    id VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    info VARCHAR(1000) NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Essential(
    id VARCHAR(20) NOT NULL PRIMARY KEY,
    phone VARCHAR(11) NOT NULL,
    address VARCHAR(200) NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE running(
    id VARCHAR(20) NOT NULL PRIMARY KEY,
    cnt INT NOT NULL,
    distance INT NOT NULL,
    FOREIGN KEY (id)
    REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE user(
    id VARCHAR(20) NOT NULL PRIMARY KEY,
    pw VARCHAR(300) NOT NULL, 
    name VARCHAR(20) NOT NULL
);